# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray

- type: subscribe
  options:
    url: https://bihai.cf/ssr/sub

- type: subscribe
  options:
    url: https://bihai.cf/vmess/sub
    
- type: subscribe
  options:
    url: https://bihai.cf/trojan/sub
    
- type: subscribe
  options:
    url: https://proxypoolss.tk/ss/sub
    
- type: subscribe
  options:
    url: https://proxypoolss.tk/sip002/sub
    
- type: subscribe
  options:
    url: https://proxypoolss.tk/ssr/sub
    
- type: subscribe
  options:
    url: https://proxypoolss.tk/vmess/sub
    
- type: subscribe
  options:
    url: https://proxypoolss.tk/trojan/sub
    
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/ss/sub
    
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/sip002/sub
    
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/ssr/sub
    
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/vmess/sub
    
- type: subscribe
  options:
    url: hhttps://proxypoolsstest.herokuapp.com/trojan/sub

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html
    
- type: webfuzz
  options:
    url: https://github.com/freefq/free

- type: webfuzz
  options:
    url: https://github.com/umelabs/node.umelabs.dev
    
- type: webfuzz
  options:
    url: https://github.com/adiwzx/freenode

- type: webfuzz
  options:
    url: https://hyt-allen-xu.github.io/free-v2ray/

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 500

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml
    
- type: clash
  options:
    url: https://bihai.cf/clash/proxies
    
# youtube xiaofeiya
- type: clash
  options:
    url: https://proxy.xiaofeiya.tk/0126/stbVzMA2cDGBKB3bGnZhsgUivxhXEPxg.yaml
    
#佛系白嫖
- type: tgchannel
  options:
    channel: foxibp
    num: 500
    
- type: tgchannel
  options:
    channel: baipiaojiedian
    num: 500
- type: tgchannel
  options:
    channel: freenodes
    num: 500
    
- type: tgchannel
  options:
    channel: freeshadowsock
    num: 500
    
- type: tgchannel
  options: 
    channel: huangjiagongyi
    num: 500

- type: tgchannel
  options: 
    channel: SSRCOM
    num: 500
    
- type: tgchannel
  options:
    channel: cnhumanright99
    num: 500
    
- type: tgchannel
  options:
    channel: ivmess
    num: 500
    
- type: tgchannel
  options:
    channel: baipiaofuli
    num: 500

- type: tgchannel
  options:
    channel: jiedfx
    num: 500
    
- type: tgchannel
  options:
    channel: RoyalhClub
    num: 500

- type: tgchannel
  options:
    channel: jingpingziyuanfenxiang
    num: 500
    
- type: tgchannel
  options:
    channel: CN_baipiao
    num: 500
    
- type: tgchannel
  options:
    channel: wzdbzdjsm
    num: 500
    
- type: tgchannel
  options:
    channel: baipiaov2
    num: 500


# 某个网站抓取
#- type: web-freessrxyz
#  options:
