# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray

- type: subscribe
  options:
    url: https://bihai.cf/ssr/sub

- type: subscribe
  options:
    url: https://bihai.cf/vmess/sub
    
- type: subscribe
  options:
    url: https://bihai.cf/trojan/sub
    
- type: subscribe
  options:
    url: https://proxypoolss.tk/ss/sub
    
- type: subscribe
  options:
    url: https://proxypoolss.tk/sip002/sub
    
- type: subscribe
  options:
    url: https://proxypoolss.tk/ssr/sub
    
- type: subscribe
  options:
    url: https://proxypoolss.tk/vmess/sub
    
- type: subscribe
  options:
    url: https://proxypoolss.tk/trojan/sub
    
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/ss/sub
    
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/sip002/sub
    
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/ssr/sub
    
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/vmess/sub

# ↓ 订阅链接############################################################################################################################
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/trojan/sub

- type: subscribe
  options:
    url: https://gitlab.com/api/v4/projects/32824328/repository/files/everydaySuB.txt/raw?ref=main&private_token=glpat-U6qeL-cHhrEVA3NDRind

- type: subscribe
  options:
    url: https://proxypoolss.tk/trojan/sub

- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/trojan/sub

- type: subscribe
  options:
    url: https://suo.yt/oDcWBfy

- type: subscribe
  options:
    url: http://free.xrenblog.com/

- type: subscribe
  options:
    url: https://paste.in/raw/AeFffC

- type: subscribe
  options:
    url: https://paste.in/raw/BiccR4

- type: subscribe
  options:
    url: https://raw.githubusercontent.com/git-yusteven/openit/main/2022/3/20-27

- type: subscribe
  options:
    url: https://v1.mk/fNk9SbH

- type: subscribe
  options:
    url: https://www.ssjh.net/api/v1/client/subscribe?token=e7aff5dfaf7ad8ba0ba2e29c15d6322e&flag

- type: subscribe
  options:
    url: https://v2r.yydsvpn.xyz/api/v1/client/subscribe?token=6062ed36141d61f4f7bc05cde9e79f5c

- type: subscribe
  options:
    url: https://github.com/git-yusteven/openit/raw/main/long

- type: subscribe
  options:
    url: https://proxypoolss.tk/vmess/sub

- type: subscribe
  options:
    url: https://jiang.netlify.app/

- type: subscribe
  options:
    url: https://tro.zqwnan.tk/vmess/sub

- type: subscribe
  options:
    url: https://pool-840979.asia1.kinto.io/vmess/sub

- type: subscribe
  options:
    url: https://gooii.ml/v2ray/sub

- type: subscribe
  options:
    url: https://youlianboshi.netlify.com/

- type: subscribe
  options:
    url: https://v2ray.banyunxiaoxi.ml/

- type: subscribe
  options:
    url: https://proxypoolss.tk/ss/sub

- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/ss/sub

- type: subscribe
  options:
    url: https://proxypoolss.tk/ssr/sub

- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/sip002/sub

- type: subscribe
  options:
    url: https://api.crhnode.top/subscribe/47740/YAoDWFoI2N/ssr/

- type: subscribe
  options:
    url: https://proxypoolss.tk/ssr/sub

- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/ssr/sub

- type: subscribe
  options:
    url: https://fast.losadhwselfff2332dasd.xyz/link/5AhOKq588TlKUisL?sub=1

- type: subscribe
  options:
    url: https://suo.yt/TXlw9fI

- type: subscribe
  options:
    url: https://suo.yt/yVCJ636

- type: subscribe
  options:
    url: https://suo.yt/7QYU8al

- type: subscribe
  options:
    url: https://v2rayshare.com/wp-content/uploads/2022/11/20221104.txt

- type: subscribe
  options:
    url: https://nodefree.org/dy/202211/20221102.txt

- type: subscribe
  options:
    url: https://tt.vg/qRvnq
# ↑ 订阅链接############################################################################################################################

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html
    
- type: webfuzz
  options:
    url: https://github.com/freefq/free

- type: webfuzz
  options:
    url: https://github.com/umelabs/node.umelabs.dev
    
- type: webfuzz
  options:
    url: https://github.com/adiwzx/freenode

- type: webfuzz
  options:
    url: https://hyt-allen-xu.github.io/free-v2ray/

# ↓ 网页模糊抓取############################################################################################################################
- type: webfuzz
  options:
    url: https://nodefree.org/p/727.html

- type: webfuzz
  options:
    url: https://v2rayshare.com/p/983.html

- type: webfuzz
  options:
    url: https://www.cfmem.com/2022/08/20220820-2022204k-v2rayclash-vpn.html

- type: webfuzz
  options:
    url: https://www.gaofumei.net/tag/ss%e8%8a%82%e7%82%b9%e5%9c%b0%e5%9d%80%e5%85%8d%e8%b4%b9%e5%88%86%e4%ba%ab/
# ↑ 网页模糊抓取############################################################################################################################

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 500

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml
    
- type: clash
  options:
    url: https://bihai.cf/clash/proxies

# ↓ clash格式订阅链接############################################################################################################################
- type: clash
  options:
    url: https://suo.yt/eaW68ok

- type: clash
  options:
    url: http://openit.ml/Clash.yaml

- type: clash
  options:
    url: https://suo.yt/0Ug05QT

- type: clash
  options:
    url: https://suo.yt/SaVCI0V

- type: clash
  options:
    url: https://github.com/git-yusteven/openit/raw/main/Clash.yaml

- type: clash
  options:
    url: https://cdn.jsdelivr.net/gh/git-yusteven/openit@main/Clash.yaml

- type: clash
  options:
    url: https://github.com/git-yusteven/openit/raw/main/pub/jiang.yaml

- type: clash
  options:
    url: https://github.com/git-yusteven/openit/raw/main/pub/mattkaydiary.yaml

- type: clash
  options:
    url: https://raw.githubusercontent.com/chfchf0306/clash/main/clash

- type: clash
  options:
    url: https://raw.fastgit.org/git-yusteven/openit/main/long

- type: clash
  options:
    url: https://mkkhack.pw/Clash

- type: clash
  options:
    url: https://nodefree.org/dy/202211/20221102.yaml

- type: clash
  options:
    url: https://v2rayshare.com/wp-content/uploads/2022/11/20221104.yaml

- type: clash
  options:
    url: https://tt.vg/eEKDO
# ↑ clash格式订阅链接############################################################################################################################

# youtube xiaofeiya
- type: clash
  options:
    url: https://proxy.xiaofeiya.tk/0126/stbVzMA2cDGBKB3bGnZhsgUivxhXEPxg.yaml
    
#佛系白嫖
- type: tgchannel
  options:
    channel: foxibp
    num: 500
    
- type: tgchannel
  options:
    channel: baipiaojiedian
    num: 500
- type: tgchannel
  options:
    channel: freenodes
    num: 500
    
- type: tgchannel
  options:
    channel: freeshadowsock
    num: 500
    
- type: tgchannel
  options: 
    channel: huangjiagongyi
    num: 500

- type: tgchannel
  options: 
    channel: SSRCOM
    num: 500
    
- type: tgchannel
  options:
    channel: cnhumanright99
    num: 500
    
- type: tgchannel
  options:
    channel: ivmess
    num: 500
    
- type: tgchannel
  options:
    channel: baipiaofuli
    num: 500

- type: tgchannel
  options:
    channel: jiedfx
    num: 500
    
- type: tgchannel
  options:
    channel: RoyalhClub
    num: 500

- type: tgchannel
  options:
    channel: jingpingziyuanfenxiang
    num: 500
    
- type: tgchannel
  options:
    channel: CN_baipiao
    num: 500
    
- type: tgchannel
  options:
    channel: wzdbzdjsm
    num: 500
    
- type: tgchannel
  options:
    channel: baipiaov2
    num: 500


# 某个网站抓取
#- type: web-freessrxyz
#  options:
